GET http://localhost:3000/api/3598fcb2-97d8-4ae=46-a3f45554cd21

### POST

POST http://localhost:3000/api/
Content-Type: application/json

{
    "name": "sdsdfghdsfsdfgsdfgsdfghsdfh"
}

### patch
PATCH  http://localhost:3000/api/e0b88205-6a43-4681-aea5-e3b5c66ad1f5
Content-Type: application/json

{
    "name": "ert4545yer46453y"
}
### delete
DELETE http://localhost:3000/api/3598fcb2-97d8-4ae6-8e46-a3f45554cd21